### ISSUE TITLE
GDPR - User functionalities

### ISSUE THREAD

**Issue by vvalvesga** [Ibercivis/odourcollect.eu#10]
Ensure that a user can know their user ID and can delete, consult, download their added data in CSV. And can unsubscribe.

**Comment by Malonsoroldan** [comment]
- A user can know their ID - DONE

**Comment by Malonsoroldan** [comment]
- A user can delete their data - NO
![image](https://user-images.githubusercontent.com/38461022/121028928-7cf81b80-c7a8-11eb-87d2-234b88bc22ca.png)

I cannot click on 'OK'

**Comment by Malonsoroldan** [comment]
- A user can consult their data - OK (my odours)

**Comment by Malonsoroldan** [comment]
- A user can download his/her data - NO

**Comment by Malonsoroldan** [comment]
- A user can unsubscribe - From what? 
a) From the case study - YES
b) From receiving notifications - NO

**Comment by frasanz** [comment]
- [X] A user can know their ID
- [X] A user can know their data
- [X] A user can consult their data (my odours)
- [X] A user can download his/her data 
- [X] A user can unsubscribe from the case study
- [X] A user can unsubscribe from receiving notifications (this has to be with deselecting "I accept to receive... while login"
- [X] Show cookies policies at bottom
