### ISSUE TITLE
GDPR - users data 

### ISSUE THREAD

**Issue by vvalvesga** [Ibercivis/odourcollect.eu#11]
User data should be saved until the end of the project and up to one year after their last login. In order to do that we have to schedule reminders (emails) at 6 months and 1 month that will unsubscribe if a user has not logged in.

**Comment by Malonsoroldan** [comment]
The location of the servers is missing on the text (Your data will be stored...).

**Comment by Malonsoroldan** [comment]
Louise: To be specific with the retention periods (when is the end of the project? To specify).

**Comment by frasanz** [comment]
An user can select if he/she wants to delete their observations

**Comment by frasanz** [comment]
Wait until @AlexAmoSfC review for automatic delete, but has to be done the following

- [X] A user can delete his/her account and decide if he/she wants to delete his/her observations
