### ISSUE TITLE
Case Study filter

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#18]
The case study filter on the map interface within the dashboard should either be removed, as it currently does nothing, or be activated so it filters accordingly.

**Comment by Javier-Gasca** [comment]
![image](https://user-images.githubusercontent.com/82105889/114988954-374d5f80-9e97-11eb-9d2c-0f7f6beb8d68.png)
The mentioned filter does not exist, check it again and send a screenshot

**Comment by Malonsoroldan** [comment]
Filtering on the front-test map seems to work (except for the date issue).

![image](https://user-images.githubusercontent.com/38461022/121032682-cac25300-c7ab-11eb-9ffc-c392c01f807d.png)

I have to define the date 4/5/21 to 5/5/21 to get the data added on 5/5/21

**Comment by EmpressNaledi** [comment]
> ![image](https://user-images.githubusercontent.com/82105889/114988954-374d5f80-9e97-11eb-9d2c-0f7f6beb8d68.png)
> The mentioned filter does not exist, check it again and send a screenshot

@Javier-Gasca here's a screenshot of the button I'm referring to.
![image](https://user-images.githubusercontent.com/12254027/122543718-fce17980-d023-11eb-9685-8817d7009828.png)

**Comment by EmpressNaledi** [comment]
> Filtering on the front-test map seems to work (except for the date issue).
> 
> ![image](https://user-images.githubusercontent.com/38461022/121032682-cac25300-c7ab-11eb-9ffc-c392c01f807d.png)
> 
> I have to define the date 4/5/21 to 5/5/21 to get the data added on 5/5/21

@Malonsoroldan this is a completely different issue and refers to the dashboard rather than the front-end

**Comment by vvalvesga** [comment]
I've deleted the dropdown case study filter
Close it
