### ISSUE TITLE
observations verified automatically

### ISSUE THREAD

**Issue by vvalvesga** [Ibercivis/odourcollect.eu#20]
in backend - dashboard -> all the observations now are supposed to be "verified" automatically

**Comment by EmpressNaledi** [comment]
When checking whether this automatic verification happens, we also need to check that when an admin unverifies an observation, that it disappears from the map in the frontend.

**Comment by EmpressNaledi** [comment]
Linked to issue #33

**Comment by vvalvesga** [comment]
i close because it's checked in #33
