### ISSUE TITLE
Could you please check the list of "subtypes of odours" under the industrial category?

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#32]
At least in my phone it is cut, I cannot see all the categories! (probably linked to screen resolution) new iPhone 12 Pro

**Comment by EmpressNaledi** [comment]
Is there something to indicate to the user that they need to scroll down to see more? Maybe add a down arrow for mobile users to indicate that the list is longer

**Comment by Javier-Gasca** [comment]
We have added an arrow at the bottom that only shows when there is part of the list that is not visible. When you get to the end of the list it disappears.
![image](https://user-images.githubusercontent.com/82105889/119643641-458a8600-be1c-11eb-9b3c-87996876489e.png)
