### ISSUE TITLE
The observations imported via CSV should be validated automatically

### ISSUE THREAD

**Issue by Malonsoroldan** [Ibercivis/odourcollect.eu#35]
To check whether imported observations are automatically validated or not. They should be validated automatically

**Comment by RosaArias** [comment]
Verified (9275) / Unverified (99) observations: To be checked
- All observations are verified automatically (issue #20 ).
- If we unverify an observation, then it has to disappear from the map in the front (issue #20 ) - in this case, the citizen should be informed, but we still have the problem with the notification, so we cannot do that (no bilateral communication). 
- With the .csv file, all the observations should be verified as well.

**Comment by EmpressNaledi** [comment]
Linked to issue #20
