### ISSUE TITLE
Grant permission to publish without validation

### ISSUE THREAD

**Issue by Malonsoroldan** [Ibercivis/odourcollect.eu#38]
What does this actually do? If it does nothing, should we hide or remove?
![image](https://user-images.githubusercontent.com/38461022/115875846-f1b80600-a445-11eb-8646-aaa28c798f13.png)

**Comment by EmpressNaledi** [comment]
@Javier-Gasca I closed 1 of the duplicates (issue #36 ) is there also another duplicate somewhere else?
