### ISSUE TITLE
Registration to the app seems not to be working fine!

### ISSUE THREAD

**Issue by RosaArias** [Ibercivis/odourcollect.eu#39]
I receive this message on Friday: 
I cannot seem to sign up with the app, I have inserted all data
requested but the button "Sign up" seems inactive, so I cannot test it
myself. 
And yesterday a different person told me the same: he was trying to register, but the process did not work (in an iPhone).
Could you please check it? Many thanks!

**Comment by JohanaSfC** [comment]
> I receive this message on Friday:
> I cannot seem to sign up with the app, I have inserted all data
> requested but the button "Sign up" seems inactive, so I cannot test it
> myself.
> And yesterday a different person told me the same: he was trying to register, but the process did not work (in an iPhone).
> Could you please check it? Many thanks!

![image](https://user-images.githubusercontent.com/83076037/116562761-10485200-a8c9-11eb-8c31-96d7fc360d53.png)

Improve the display of the "Age" field. It is common that people do not fill in this information and therefore cannot register. 
(Underline the field that is missing to be completed)

**Comment by EmpressNaledi** [comment]
This is no longer a bug but a usability issue that should be addressed before closing

**Comment by EmpressNaledi** [comment]
Usability feedback:
I think that the problem for the users is that the field "age" is not so much visible and they may skip this field, so the registration is not completed and does not work (more than a bug issue). Maybe we can make this field more visible with a square or something to select from the drop out list, so new users do not miss it and it does not happen again

**Comment by EmpressNaledi** [comment]
@Javier-Gasca can you provide a description of the solution implemented along with a screen dump please

**Comment by Javier-Gasca** [comment]
I have placed a line under the age field so that it shows that it is a field and when you do not select any age, a red text appears just below.
![image](https://user-images.githubusercontent.com/82105889/119617190-d738ca00-be01-11eb-9f7a-dd417b392d2d.png)
![image](https://user-images.githubusercontent.com/82105889/119617998-b15ff500-be02-11eb-9fc5-adce1b9e95a8.png)
