### ISSUE TITLE
Filtering/Validation/Classification Bug

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#43]
A detailed description with screenshots is provided in the attached

**Comment by EmpressNaledi** [comment]
[Bug Report_280421.docx](https://github.com/Ibercivis/odourcollect.eu/files/6391461/Bug.Report_280421.docx)

**Comment by vvalvesga** [comment]
I can't to reproduce the same case.
As we've changed a lot of things I ask you try again. Now, in frontend, we don't show unverified observations. And we've also changed time filter.
In the dashboard's map is showing unverified observations and the observations list is below of the map

**Comment by EmpressNaledi** [comment]
@vvalvesga I believe this issue has been addressed with the changed time filter so can be closed.
