### ISSUE TITLE
Filtering in the mobile verison (duplicated n#19)

### ISSUE THREAD

**Issue by miguelherpas** [Ibercivis/odourcollect.eu#44]
When you want to filter in the mobile, it is not possible to differenciate between the scale for intensity and hedonic tone. I am currently using a Xiaomi Mi A1. I propose splitting the parameters in two different lines, but it mighht
Please, find attached the screenshot of this problem. 
Best regards!
![WhatsApp Image 2021-04-30 at 11 56 18](https://user-images.githubusercontent.com/83075623/116679940-642b6780-a9ab-11eb-81b5-c12911934b3f.jpeg)

**Comment by frasanz** [comment]
Check proposed solution in fronttest.odoourcollect.eu and close if agreed
<img width="360" alt="Captura de pantalla 2021-07-19 a las 17 42 35" src="https://user-images.githubusercontent.com/456573/126187887-80ada34f-a944-4874-8748-af49ce29f4c4.png">

**Comment by miguelherpas** [comment]
We checked the usability of this solution, and we consider that it is a good solution. Despite losing the time option in the filtering, the visualization in smartphones is not that important.

So it is good for us!
