### ISSUE TITLE
Zone Admin - Email notification set-up

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#48]
The idea of developing an email notification system that can be generated [for Zone Admins] when specific criteria are met defined by select variables. Potential variables could include:
no. of observations within a  24hr period
Odour type/s list selection
Waste
Waste water...
Hedonic tone - customisable - for each category selected

-> An email should be sent to the zone admin  if ALL the conditions are met.

**Comment by Malonsoroldan** [comment]
![image](https://user-images.githubusercontent.com/38461022/117455281-547dc700-af47-11eb-9aed-3b2d54458db9.png)
Could be added under the 'users' box

**Comment by Malonsoroldan** [comment]
![image](https://user-images.githubusercontent.com/38461022/121006515-44007c80-c791-11eb-9add-e293cdba24fe.png)

This has been pushed to the live backend sever, I guess by mistake, as it cannot be used the way it is now:
- Number of observations and time period cannot be specified "____ observations added for the past ____ hours"
- Unable to select different odour types
- Hedonic tone cannot be specified per odour type
- To add intensity and intensity per odour type

**Comment by vvalvesga** [comment]
Yes, it's not resolved yet

**Comment by vvalvesga** [comment]
![imagen](https://user-images.githubusercontent.com/48445869/122018854-88a89b00-cdc3-11eb-9c00-58be826de961.png)

In this issue i have some questions
Do you want select only one odour type (parent odour types)? Or more?
For hedonic tone i will use a slider as wwe have in frontend's filters

I don't know then if it's only a record, that is, a type of smell with its hedonic tone
Or you want to add as many records as you want with their type of smell and their hedonic tone. This complicates it something more

**Comment by Malonsoroldan** [comment]
We need to 
- select multiple odour types (sub types don't matter that much) 
- intensity, more than hedonic tone; 
- number of observations
- the geography needs to be limited 

In essence, it should be something like this example (in Bold, things that the user should be able to set up)
**5** observations + **Waste + Waste Water** + **...** categories + intensity **equal/over 3** + period of **24** hours -within the case study limits-   

An email will be sent out if the rule applies.

**Comment by vvalvesga** [comment]
What does mean categories? odour types?
Do you have to indicate the number of observations?
how would this work? catch when there are 5 observations instead of the time period having passed?
geography limited? What does mean it? This issue is about a zone

**Comment by Malonsoroldan** [comment]
Categories = odour types
Yes, we'd like to be able to say X observations **within** Y time period (X and Y to be set up by the user, e.g. 3 observations within a 24h-period or 5 observations within an 8h-period)
Limited geography = zone

**Comment by vvalvesga** [comment]
Done

**Comment by Malonsoroldan** [comment]
Just got a test email notifications, 2 amends to do ASAP:
- Any email should be sent using BCC
- The notification should ONLY be sent to the Zone Admin

**Comment by EmpressNaledi** [comment]
In addition, the wording of the email should be changed to:
You are receiving this email as an OdourCollect Zone Administrator because there have been new observations made in your area.  

The new observations are: 
** are you able to provide a hyper link to the new observations @vvalvesga ? If not, can you provide a summary that includes the time, date, location, odour type, sub-type, intensity, hedonic tone and any comment that may have been included?**

**Comment by vvalvesga** [comment]
link to what?
The application when you click on an observation doesn't return a valid url.
maybe more information as you say, but how do you want it? somehow you have to know what is that

**Comment by EmpressNaledi** [comment]
For example:

The new observations are:

    
![image](https://user-images.githubusercontent.com/12254027/124114953-20b1b000-da65-11eb-9f6b-aaec0000aac0.png)

**Comment by EmpressNaledi** [comment]
@vvalvesga if this can be addressed then all issues related to zone admin email notifications should be closed and have been dealt with.

**Comment by vvalvesga** [comment]
Yes, that is
I'm wit it @EmpressNaledi

**Comment by EmpressNaledi** [comment]
Great! Thanks @vvalvesga

**Comment by vvalvesga** [comment]
Done, check it
