### ISSUE TITLE
Emails sent to user (laravel) seem not to indicate username properly

### ISSUE THREAD

**Issue by AlexAmoSfC** [Ibercivis/odourcollect.eu#49]
"name" var is set to "username" instead of the real user name. 
![Anotación 2021-05-25 114610](https://user-images.githubusercontent.com/83209147/119476929-d1ce7780-bd4e-11eb-9f1e-21584414d415.png)
EDIT: (not email template related, but variable storage related)

**Comment by frasanz** [comment]
The problem is that the username is not stored properly in the database. It saves "username" instead of the name provided while registering

**Comment by AlexAmoSfC** [comment]
@frasanz ACK. Since all the user information is then lost, and having "username" string all around the database will preclude us from testing, I'd suggest an approach for correcting the username of users already in database, in parallel while you fix the issue. It should be just a quick SQL query, but we have to think about the specific query (update username column copying the value from the user id column, prepending the string "user", so it becomes "user12345" for example). 

TBD in next followup meetings.

**Comment by frasanz** [comment]
I can to that if you want. (to put user_XX) as username.

The problem was that it was decided to remove "username" from the table
(because GDPR) but we saw it was a bad idea, so we need to fix it.

Fran

**Comment by AlexAmoSfC** [comment]
Actually, there is no need to do that to be GDPR compliant (lots of apps do have user ids chosen by he users themselves).
So, can you recover the data from a database backup before such a significant update to DB structure, or is the username information lost? A rollback would be ideal.
In second scenario, yes, please insert "user_nnnnn" as username in order to replace lost data.

**Comment by frasanz** [comment]
Yes, that´s the idea, to recover

Fran

**Comment by EmpressNaledi** [comment]
@AlexAmoSfC 
Just to note that users should be informed that there username will be on public display.
The UK GDPR specifically includes the term ‘online identifiers’ within the definition of what constitutes personal data.

"An individual’s social media ‘handle’ or username, which may seem anonymous or nonsensical, is still sufficient to identify them as it uniquely identifies that individual. The username is personal data if it distinguishes one individual from another regardless of whether it is possible to link the ‘online’ identity with a ‘real world’ named individual."

**Comment by frasanz** [comment]
I changed username to user_xx in the database.

So, in order to clarify the final behavior. My idea is that people can
introduce their username, but it is not going to be visible in the platform
for others (including administrator). Is that correct?

Fran

**Comment by AlexAmoSfC** [comment]
> @AlexAmoSfC
> Just to note that users should be informed that there username will be on public display.
> The UK GDPR specifically includes the term ‘online identifiers’ within the definition of what constitutes personal data.
> 
> "An individual’s social media ‘handle’ or username, which may seem anonymous or nonsensical, is still sufficient to identify them as it uniquely identifies that individual. The username is personal data if it distinguishes one individual from another regardless of whether it is possible to link the ‘online’ identity with a ‘real world’ named individual."

@EmpressNaledi: 
Sure. GDPR defines user ids as PII. I totally agree (I have a background in cybersecurity, so I couldn't agree more and I love the example of "doxing" you provide 8-) ).
My point in this regard would be: 
- better not to perform deep, significant changes in app/db structure at this point. This is a case of regression affecting UX in a visible way. 
- GDPR compliant apps can store such data if properly stated and processed. User id is totally ok if a) we state that is going to be used for things like internal email communication/engagement purposes; c) will not be accessible to other users in any way; b) only the SUPERADMIN is going to be able to access such data (it needs to do so as data controller, correct me if i'm wrong)

@fran:
as soon as @EmpressNaledi agrees with my last comments, I think you can proceed in the way you suggest. (ask name, keep name, dont show name in public front)

**Comment by AlexAmoSfC** [comment]
Clarification: there is an autogenerated "moniker" which is not PII, and that moniker is the thing shown publicly in map.
The username chosen by the user him/herself is going to be used only for internal communication (via email) purposes.
I'll read the GDPR texts and, if nothing is stated in a way that does not match the behaviour and processing of the data, I will close this issue.

**Comment by AlexAmoSfC** [comment]
Pending confirmation that this is not happening anymore @frasanz

**Comment by frasanz** [comment]
It is not storing the username in the database when registering, needs to be fixed
