### ISSUE TITLE
Layout problems in the hedonic tone screen

### ISSUE THREAD

**Issue by miguelherpas** [Ibercivis/odourcollect.eu#50]
Attached two screenshots of the issue, where the texts are overlaped. The smartphone was  a Xiaomi Redmi 8A with Android 10. 

![Screenshot_2021-05-25-11-59-55-844_es nobone manchesterwebapp](https://user-images.githubusercontent.com/83075623/119480986-7e5e2880-bd52-11eb-8ee5-55528e8760aa.jpg)
![Screenshot_2021-05-25-11-59-20-065_es nobone manchesterwebapp](https://user-images.githubusercontent.com/83075623/119480993-8027ec00-bd52-11eb-9c82-71dd6a7493e8.jpg)

Can it be posible to make the circle more fluid so it can go up a bit when there is limited vertical space?

Thanks by advance, if you need any further information do not hesitate to ask for it.

**Comment by AlexAmoSfC** [comment]
I would suggest to reduce textview.setTextSize in levels -4/4 for a quick patch, but fluid layout is recommended (there's plenty of vertical space on top of the circle)

**Comment by Javier-Gasca** [comment]
I have made a few small changes. Could you please check how it looks now and provide a screenshot?

**Comment by AlexAmoSfC** [comment]
Smart strategy, adding extra step views so you don't have to care about layout fluidity. 
IMHO it's a great change and it solves the problem.
Thoughts, @miguelherpas @JohanaSfC?

**Comment by miguelherpas** [comment]
Good morning! Thanks for the work @Javier-Gasca ! I think it solves the problem most of the time. Nevertheless, when width resolutions are lower than 300 (e.g in the case of Galaxy Fold in developers mode of Chrome (280x653) the problem persists. I am not sure if that is still a problem or it is only happening in the developer's mode. 
What is your opinion?

![image](https://user-images.githubusercontent.com/83075623/121469402-b43f1600-c9bc-11eb-9657-e25dcd8ff7c2.png)

**Comment by Javier-Gasca** [comment]
I have increased the space between the two texts and now I see it well. I close the issue, if you still have a problem with the visualization, reopen it
