### ISSUE TITLE
Nice odours can have an unpleasant clasification

### ISSUE THREAD

**Issue by miguelherpas** [Ibercivis/odourcollect.eu#51]
This issue is not a "proper" problem, I just wanted to open a discussion about the fact that nice odours can have an unpleasant classification. I wanted to know your opinion about which is the best way to clarify this situation.

**Comment by AlexAmoSfC** [comment]
@miguelherpas here's my take on that, IMHO.

Conversely, unpleasant odours can be scored as pleasant. This is a design decision (or lack thereof), that would imply redesigning the list of odour types/subtypes in a way that we should specify if an odour type has to be always positive or always negative. All in all, this is the kind of decisions that have to be took before even writing a line of code IMHO. On top of that, we have to prioritize, and time runs out. Hence, it is with great sorrow that I'd suggest not making any code refactoring to tackle this question, and accept this potential inconsistency for the sake of simplicity.

**Comment by frasanz** [comment]
I do agree.

**Comment by frasanz** [comment]
I mean, I do agree with Alex's suggestion. There are issues that might be a
lot of effort to make (in terms of hours) and short benefit. And we should
avoid it at this point.

Fran

**Comment by AlexAmoSfC** [comment]
If you are OK with that, I proceed to tag as wontfix and close. This does not take the fact that we'll take this shortcoming of the app into account for future iteration on the long run.
