### ISSUE TITLE
Download of all observations in OC does not work correctly

### ISSUE THREAD

**Issue by JohanaSfC** [Ibercivis/odourcollect.eu#55]
When you sign in as SUPERADMIN, you can download all observations available in OC.
![image](https://user-images.githubusercontent.com/83076037/120661170-a5e97b00-c44d-11eb-8fe3-af2483418961.png)

The APP shows this window, where the user can see that the app is running this activity.
![image](https://user-images.githubusercontent.com/83076037/120661734-26a87700-c44e-11eb-96e2-e30961ae5972.png)

But then this message appears
![image](https://user-images.githubusercontent.com/83076037/120648163-f0b0c600-c440-11eb-8382-a067b9f94d8d.png)

Despite the above message, the XLSX file is download after waiting a few minutes in the previous window.

The message: error invalid response, that appears may be because the browser interprets that filed download as a document that it is trying to display on screen.

**Comment by frasanz** [comment]
I increased to 120 seconds the time for execution php

**Comment by frasanz** [comment]
Test needed
