### ISSUE TITLE
Unable to upload observations on the front test

### ISSUE THREAD

**Issue by Malonsoroldan** [Ibercivis/odourcollect.eu#56]
I cannot upload observations through the front test as geolocation cannot be activated as is not a 'secure' web
![image](https://user-images.githubusercontent.com/38461022/121042144-aff3dc80-c7b3-11eb-8222-bf1c5a8151dd.png)

**Comment by Javier-Gasca** [comment]
Try putting https in the url instead of http

**Comment by Javier-Gasca** [comment]
It works for me

**Comment by frasanz** [comment]
Yes, it´s working under https
