### ISSUE TITLE
Confirmation email not received after registering on Pre (front test)

### ISSUE THREAD

**Issue by Malonsoroldan** [Ibercivis/odourcollect.eu#57]
ID 1191 – Didn’t receive the confirmation email

**Comment by frasanz** [comment]
We are able to set the user/password in de development server. What I did was to: 
1) include .htaccess file not to access to .env
2) add to laravel/config/app.php the following:
`  'debug_blacklist' => [
    '_COOKIE' => array_keys($_COOKIE),
    '_SERVER' => array_keys($_SERVER),
    '_ENV' => array_keys($_ENV),
    ],`

so we are not going to dump environment variables when an error happens

@AlexAmoSfC , I need email user / password for the fronttend server

**Comment by AlexAmoSfC** [comment]
Closed since the issue was left open accidentally. Last coment by @frasanz explains the solution taken.
