### ISSUE TITLE
Observations attached to a deleted case study zone

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#61]
Observations made in the Southall case study zone are being inconsistently assigned to zone 24 and zone15. Zone 15 was deleted some time ago and any of the old observations should be appended to zone 24. There should be a hard delete of Zone 15 after this to prevent any new observations from being assigned. Currently all the June observations seem to have been assigned to the deleted zone.

**Comment by vvalvesga** [comment]
if you download the track in https://admin.odourcollect.eu/admin/zone/24 you can show all observations included June observations.
and if i can go to https://admin.odourcollect.eu/admin/odour/list and i filter by zone Southall i can see June observations.

I am going to delete the case studies marked as deleted and in the delete functionality I will actually delete the case study

**Comment by vvalvesga** [comment]
I've moved everything assigned to zone 15 to zone 24.
We've decided only to delete zone 15 (Southall marked as deleted) for the moment. Check if all is correct for Southall zone.
Close issue

**Comment by EmpressNaledi** [comment]
@vvalvesga now the download for the zone has duplicate observations (see attached download)
[odours (15).xlsx](https://github.com/Ibercivis/odourcollect.eu/files/6701172/odours.15.xlsx)

**Comment by vvalvesga** [comment]
It's true. Solved it

**Comment by EmpressNaledi** [comment]
Thanks @vvalvesga
