### ISSUE TITLE
Language in the app when you enter first time (based on feedback of users)

### ISSUE THREAD

**Issue by miguelherpas** [Ibercivis/odourcollect.eu#63]
When you open the app for the first time, English is the default language. This can be an inconvenience for users that do not know English, especially old people. 

I would suggest putting by default the language of the device. I do not know if it is possible to change it, but it was one of the problems that the users detected.

Thanks in advance

**Comment by AlexAmoSfC** [comment]
this is a two layer approach:

@frasanz will focus on server side browser language detection
@vvalvesga will focus on webview controller of mobile app, in order to ensure that it the sends the proper locale to server

**Comment by vvalvesga** [comment]
Done

**Comment by AlexAmoSfC** [comment]
Nice. Will you or have you pushed to production at some time this week?

**Comment by vvalvesga** [comment]
All is updated. About this issue, it requires new session or delete cookies. Or control + F5. If you want we review navigator's language every time user loads page, you must specify it

**Comment by AlexAmoSfC** [comment]
I understand that you check language of user agent only when no language is set in cookies, then you store language. right?
to me, it's a fair approach

**Comment by vvalvesga** [comment]
that is it
