### ISSUE TITLE
Automatic verification

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#64]
For some reason, some observations are not automatically being verified and I'm not sure why. The observation below was taken today in Southall but is showing as pending. As a result, I haven't received the email notification that I set up.
![image](https://user-images.githubusercontent.com/12254027/123432647-7fd57780-d5c2-11eb-901b-4549731818f9.png)

**Comment by vvalvesga** [comment]
in the code it puts verified to 0 if the user does not have publication permission
you want it to always be verified to 1 right? I change it?

**Comment by EmpressNaledi** [comment]
I'm not sure what publication permission means or how it is obtained. So, yes please set any observation to always be verified to 1.

**Comment by vvalvesga** [comment]
Ok, done.
