### ISSUE TITLE
Zone admin Email notifications

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#65]
I set-up the email notifications for Southall last week with the following parameters but none of us have received an email even though the conditions have been met.
![image](https://user-images.githubusercontent.com/12254027/123924064-80368f80-d981-11eb-8ced-cea17bca0663.png)

**Comment by vvalvesga** [comment]
I think there are no observations that meet a hedonic tone between 1 and 4

**Comment by EmpressNaledi** [comment]
You are right and that's my error - I should have set it to minus! Thanks. I'll close the issue for now
