### ISSUE TITLE
Zone admin Email notifications disclose recpts

### ISSUE THREAD

**Issue by AlexAmoSfC** [Ibercivis/odourcollect.eu#66]
Please, put the recipients in CCO, or send emails in batches of one by one. both solutions would be acceptable.
I attach screen cap.
![Anotación 2021-07-01 141200](https://user-images.githubusercontent.com/83209147/124122411-590dba00-da76-11eb-8dd2-08cb57442bc7.png)

**Comment by vvalvesga** [comment]
It's done, i close
i put the recipients in CCO
