### ISSUE TITLE
[Zone manager notifications] We are notified of the very same observations every hour.

### ISSUE THREAD

**Issue by AlexAmoSfC** [Ibercivis/odourcollect.eu#67]
It seems that we all zone managers are receiving the very same observations time after time each hour, which would only make sense if the were new, but doesn't if we were notified just an hour ago. We get the same numbers again.
This is happening since today @ 13h
The same email received @ 14h and at @ 15h.

I temporarily disabled related crontab task until you act, due to complains from managers.
Thanks

**Comment by EmpressNaledi** [comment]
Hi @AlexAmoSfC I think this is happening because you have set the parameters to 1000hrs! and 1 observation. As such, you will get 10000 emails! (1 per hour for 1000hrs). The system checks whether the parameters have been met every hour sp it's more about your settings,

**Comment by vvalvesga** [comment]
I put those parameters to do some tests
I forgot to remove it, sorry

**Comment by vvalvesga** [comment]
about sending the same comments ...
it's a problem?
I think that if you put that for the notification to reach you it has to be when 10 observations occur in 3h, it makes sense to send them all and not only those that have occurred in the last hour, I don't know if I explain myself

**Comment by vvalvesga** [comment]
@AlexAmoSfC close if it's not a problem

**Comment by EmpressNaledi** [comment]
@vvalvesga I'm not sure what you mean, can you explain please?

**Comment by vvalvesga** [comment]
that if you put these conditions
2 hours
3 observations

1) 9:10 -> 1 obs
2) 9:40 -> 1 obs
3) 9:50 -> 1 obs
4) 10:40 -> 1 obs
5) 10:50 -> 1 obs
6) 11:30 -> 1obs
7) 12:30 -> 1obs

First mail at 10-> 1,2,3
second mail at 11-> 1,2,3,4,5
third mail at 12 -> 4,5,6
no email is sent at 1pm, there are no 3 observations in the last 2 hours

I ask if it is correct
Alex says that observations are repeated in the emails
that is to demonstrate that the conditions are met and those observations that comply with the established are returned

if all is ok, we close this issue

**Comment by EmpressNaledi** [comment]
I think this is fine @vvalvesga . However, if you add the additional details that I outlined here [https://user-images.githubusercontent.com/12254027/124114953-20b1b000-da65-11eb-9f6b-aaec0000aac0.png] Issue # 48, I think it will help administrators identify and clarify even whatever parameters they have chosen.

**Comment by EmpressNaledi** [comment]
![image](https://user-images.githubusercontent.com/12254027/124263453-2c67aa00-db2b-11eb-9b74-87dc533a8420.png)

**Comment by vvalvesga** [comment]
ok, that is other issue
close this

**Comment by AlexAmoSfC** [comment]
@Malonsoroldan has kindly explained the functionality to me. Now I have a more clear grasp of it, but still some concerns about that. I will test on my own and let you know in case I have questions.
By the way, I restore the cron task that I freezed yesterday because of this issue.
