### ISSUE TITLE
Zone admin Email notifications (see also #65)

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#68]
@vvalvesga I think the notifications might be going to all of those assigned to a zone, instead of the Zone Admins - is it possible for you to check? That might be why so many registered users received the email notification.

**Comment by Malonsoroldan** [comment]
We just want the notifications to go ONLY to the Zone admins, and not everyone assigned to a zone.

**Comment by vvalvesga** [comment]
ok, the code was wrong
I took advantage of a function that had to return the zone admin and actually returns all those assigned to that zone
I change it

**Comment by EmpressNaledi** [comment]
Okay, if this is soled the issue can be closed

**Comment by vvalvesga** [comment]
done

**Comment by EmpressNaledi** [comment]
Thanks
