### ISSUE TITLE
Login error pop-up when adding an observation

### ISSUE THREAD

**Issue by Malonsoroldan** [Ibercivis/odourcollect.eu#69]
While being logged in, I try to add a contribution and get this pop-up at the end of the process:
![image](https://user-images.githubusercontent.com/38461022/124296518-584e5400-db5a-11eb-9af9-83e55bc89d7d.png)
However, the contribution exists on the map
![image](https://user-images.githubusercontent.com/38461022/124296614-73b95f00-db5a-11eb-819c-8f33a06d5591.png)
To check

**Comment by Malonsoroldan** [comment]
![image](https://user-images.githubusercontent.com/38461022/124770089-51e52100-df3a-11eb-87a7-2f29323a02b2.png)

Same issue yesterday, but the observation is added

![image](https://user-images.githubusercontent.com/38461022/124770277-7fca6580-df3a-11eb-87a4-f2e8fca6d501.png)

**Comment by AlexAmoSfC** [comment]
![possible error from uganda](https://user-images.githubusercontent.com/83209147/125948753-591aca96-f11f-4179-b6e7-c7962ccc6310.png)

Attaching this screen capture with additional information observed in laravel's storage engine log. 

Please check out /var/www/html/api-odourcollect/public/laravel/storage/logs/laravel.log (06/07, 15:31)

**Comment by frasanz** [comment]
I cant reproduce the error

As seen in the log, when creating an odor:

(1) The system creates an entry in the database in the odor_emails table (it uses the location->place value (the column place inside the location table))
(2) It send an email (this functionality is disabled)

Not sure why, in this case the system was not able to resolve the location (as you can see in the table,  there are few cases where place is not resolved)

As far as I can see, this location->place value is not send within the email (in fact, as said, we are not sending the emails for a new odor) , but we are storing it in the location column inside the odor_emails table. When this is null, it raise this error.

So, the workaround solution (already done) is to comment out the storing on the odor_emails table (as we are not sending emails) when adding an observation

**Comment by AlexAmoSfC** [comment]
I can directly ask to the user to tell us the brand and model of terminal, as well as some basic configs and the android version. 
My guess is that we are supporting combinations of setups that trigger this.

A per solving the problem, it may solve it, but we would continue having observations with no location (near to useless), right?

**Comment by frasanz** [comment]
You have the location (latitude and longitude), but the library can not
resolve some details of the  place (that is, the city)

**Comment by frasanz** [comment]
I mean, is not a terminal problem, but a library problem resolving the
city, street, etc from the geolocation

Fran

**Comment by frasanz** [comment]
Mapbox resolve street, country, etc. from latitude, longitude here:

https://github.com/Ibercivis/odourcollect.eu/blob/main/api-odourcollect/public/laravel/app/Http/Controllers/LocationController.php

But it fails in a few cases (not sure why, may a mapbox bug)

Fran
