### ISSUE TITLE
Zone Admin - Email notification

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#70]
Can we add to the details currently provided in the email notification, which timezone the database is using. People will not understand otherwise, why there is a difference between the timestamp in the email compared with what the observe in OC, which is for crucial for the Environmental Officers acting on these alerts.

Also, the Officers need to know where they are going to in the field to investigate these complaints, so including the Address field in the notification is also required.

**Comment by vvalvesga** [comment]
Done, i added address field and i put UTC after time

**Comment by EmpressNaledi** [comment]
Thanks @vvalvesga !

**Comment by Malonsoroldan** [comment]
Ole!!
