### ISSUE TITLE
Check the Spelling for Odour across the App and Datbase

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#71]
Across the front-end and back-end odour is inconsistently spelled and various from odour to odor. Please can check both and edit so that we use odour consistently. See images below for some examples.
![image](https://user-images.githubusercontent.com/12254027/125054612-51fe3180-e09e-11eb-8fcd-7aa1524add80.png)
![image](https://user-images.githubusercontent.com/12254027/125055121-cdf87980-e09e-11eb-994f-c6035fb6251d.png)
![image](https://user-images.githubusercontent.com/12254027/125055240-e36da380-e09e-11eb-8da6-e3a12b360bf1.png)

**Comment by frasanz** [comment]
Done in the database

**Comment by frasanz** [comment]
Not found in the i18n files (translation files)
