### ISSUE TITLE
Asignation of observations to case studies

### ISSUE THREAD

**Issue by miguelherpas** [Ibercivis/odourcollect.eu#72]
Same issue as #62. We want to download data for the analysis of a case study (the zone name starts with Masquefa in this case).
Please @vvalvesga check it out that is not functioning as expected and the last observation that appears when you filter is on 21/06 meanwhile in that zone there are observations from yesterday (13/07).  We have in this case 26 observations that are not assigned to the case study but are located into it. 

@AlexAmoSfC @JohanaSfC are trying to figure out which is the problem in this case, but we think that it is related to the assignation of observations to case studies. There is an issue in some locations, as you can see if you check the general database (for example the observations in Southall are well assigned to the case study, but in the case of Masquefa or Castellanza it is not happening for the last 3 weeks). 

We have the following doubt: What is the way that OC assigns the observations to a case study? Is it done periodically? How can we be sure that I have all the observations in the file I download when I filter in the BackOffice?

I also submit a couple of pictures that refer to that problem, in the first one you will see the incongruences in the zones. The observation highlighted is in the area of Masquefa's case study but it is not assigned to it. The second one is related to the server, where we saw that all the observations over 10000 are not assigned to the case study zone for this study on Masquefa. If you have any other questions, just tell us!

![image](https://user-images.githubusercontent.com/83075623/125786398-8e5ed663-1fbb-4148-bbc6-f39588e55685.png)
![image](https://user-images.githubusercontent.com/83075623/125786571-df80fa7f-710c-4bed-a25e-771e107dbde4.png)

PD: It would be really helpful for us to have this solved next Monday, as we want to present the analysis that afternoon. We would only need all the observations in that area of study, not only until 21/06. If not we can do it by hand, but it would take us some time...

**Comment by vvalvesga** [comment]
Creating an odor, it is saved with the basic fields. A location is created. And then a method is called to associate the zone.
In this method (zoneAttach) all zones are traversed and its points are traversed for each area and polygons are created.
Check if the latitude and longitude of the added point is in any of the polygons.
If it is found in any, then it checks if the user who has added it belongs to the zone and if it is true then it adds the zone to the zones associated with the smell.

**Comment by vvalvesga** [comment]
I've only see theese observations


![imagen](https://user-images.githubusercontent.com/48445869/126328172-121bd763-9dc5-46ff-b7f5-50f4cbb95f53.png)

**Comment by vvalvesga** [comment]
![imagen](https://user-images.githubusercontent.com/48445869/126328260-7ed9a8ee-1086-4cb6-b4c3-0558eee896b5.png)

**Comment by vvalvesga** [comment]
zone 29 masquefa
![imagen](https://user-images.githubusercontent.com/48445869/126328308-5b52f2e1-c03c-4ef6-9814-f4410c8fe9ca.png)

**Comment by vvalvesga** [comment]
zone's points
![imagen](https://user-images.githubusercontent.com/48445869/126328393-2d7e5e9e-2b76-4c18-b3da-e53fb3f36e12.png)

**Comment by vvalvesga** [comment]
I have seen this observation from 13/07 and you can see how the user who added it is 1408 and this is not assigned to the Masquefa area, I think that is why it has not been added

**Comment by vvalvesga** [comment]
![imagen](https://user-images.githubusercontent.com/48445869/126328505-7d95355a-4822-49da-a7e1-bb6083d8f2cf.png)

**Comment by vvalvesga** [comment]
That has been my investigation :)
Check it and decide what to do. If you want, close issue or maybe change something/create new issue

**Comment by miguelherpas** [comment]
Thanks for the investigation Víctor. 
I've checked the observation you commented on before and it has been certainly done inside the area of study. 

Nevertheless, I have some doubts:

- What is assigned to a zone? a user or an observation?
-Why some observations from the same user in the same point are assigned and others not? (In this case, we noticed the date when it stopped assigning the observations to an area was 21st of June)

I still miss which is the exact problem that causes this. If you want, check the following excel file where I gathered all the observations in the area (finding manually all the ones that were not assigned automatically into the zone) You can notice easily that the observations suddenly stop being assigned once they reach the ID number of 10000. That is one of the interesting things that we realized the other day...

[OC_CanMata.xlsx](https://github.com/Ibercivis/odourcollect.eu/files/6849020/OC_CanMata.xlsx)

**Comment by vvalvesga** [comment]
Both, user and odour are assigned to a zone

**Comment by miguelherpas** [comment]
PD: I just checked the issue and it is no longer happening, thanks for solving it. 
But I didn't get exactly why this has happened to us. If you remember we had this problem twice already and I still don't get what is wrong. As it is a recurrent issue, I think that we should try to find a permanent solution...

Is there any automatism that is not working correctly? How did you solve it? Do you think this will happen in the future?

**Comment by vvalvesga** [comment]
If it is found in any, then it checks if the user who has added it belongs to the zone and if it is true then it adds the zone to the zones associated with the smell.

**Comment by vvalvesga** [comment]
i didn't make any changes
The problem I see is that you add observations with a user that is not assigned to that zone.

**Comment by vvalvesga** [comment]
having that clear, you use a user that belongs to that zone. Then with that user you add observations.
I have not invented this logic, I only tell you that this is the procedure.

**Comment by vvalvesga** [comment]
for me what you say about the id greater than 10000 does not make sense, that is, I do not see any relationship with any of the code

**Comment by vvalvesga** [comment]
I think I have already found the reason why all the new observations came out yesterday @miguelherpas .

**Comment by vvalvesga** [comment]
![imagen](https://user-images.githubusercontent.com/48445869/126473850-86b357e5-c334-4137-9463-9d77e1fa6712.png)

**Comment by vvalvesga** [comment]
there is no process. But if there is this button, if you press it then it goes through all the areas, all the smells and checks if it is within a polygon, if so, then it associates the observation with the area.
Important: in this case, it does not check if the user is also associated with the zone.

Conclusion: I believe that someone has pressed that button and that is why the observations that were not assigned to their zone have suddenly been assigned to their zone.

**Comment by frasanz** [comment]
Solution: If an observation belongs geographically to a Zone, put this observation to a zone.
