### ISSUE TITLE
Hedonic tone semantics inconsistence (app interface != database and export files)   

### ISSUE THREAD

**Issue by AlexAmoSfC** [Ibercivis/odourcollect.eu#75]
OC hedonic tone is treated inconsistenlty across the different components of OC (user frontoffice, admin backoffice, internal database, data export files)

See following list of values in user frontend (numerical values and related literals):

- -4 Extremely unpleasant
- -3 Very unpleasant
- -2 Unpleasant
- -1 Slightly unpleasant
- 0 Neutral
- 1 Slightly pleasant
- 2 Pleasant
- 3 Very pleasant
- 4 Extremely pleasant

See following list of values for admin frontend AKA backoffice (numerical values and related literals):

- -4 Extremely unpleasant
- -3 **Moderate unpleasant**
- -2 Unpleasant
- -1 Slightly unpleasant
- 0 Neutral
- 1 Slightly pleasant
- 2 Pleasant
- 3 **Moderate pleasant**
- 4 Extremely pleasant

Values in 3 and -3 are not _moderate_ (un)pleasant, but _very_ (un)pleasant. 

OC also has the wrong literal values stored in its very core, in the table `odor_annoys`
![Anotación 2021-07-28 214035](https://user-images.githubusercontent.com/83209147/127385449-bd39833c-d301-40c1-b609-4af9eeaecf1b.png)

There is no _moderate_ version of an hedonic tone, we should always stick to the following semantic scale:

- neutral
- slight "adjective"
- "adjective alone"
- very "adjective"
- extremely "adjective" 

**IMPLICATIONS**

Analysts have been viewing the wrong concept _moderate (un)pleasant_ thinking that the odour observation had a bit lesser hedonic tone than simple "(un)pleasant", while in fact the users were expressing the opposite ( _very (un)pleasant_ is ABOVE (un)unpleasant, in terms of intensity). This has affected the perception of analysts in admin backoffce as well as in XLSX exported files.

Internal constants in OC code like MODERATE_UNPLEASANT and MODERATE_PLEASANT should be corrected in some parts of the i18n and l10n.

Also, the hedonic tone mapping dictionary used in some of the internal analysis tools (see IBERCIVIS Jupyter notebook) should be reviewed and corrected too. 

![Escala deseada (la que se ve)](https://user-images.githubusercontent.com/83209147/127383262-6777a91b-1363-4d0b-a48d-0f99471d597c.png)

**Comment by AlexAmoSfC** [comment]
Hi @frasanz. Thanks for the quick response pushing a fix.
I would like also to ammend the code internals, since some constant values were declared in a flawed fashion. Check out the literals MODERATE_UNPLEASANT and MODERATE_PLEASANT, which should become VERY_UNPLEASANT and VERY_PLEASANT.

Can you take a look? I estimate that this refactor, if performed correctly, does not have any potential for causing any sort of error

**Comment by frasanz** [comment]
Yes, I did that with the slugs (moderate-pleasant, moderate-unpleasant) ,

Regarding these two literals, there are used in translation variables for
the webview. Changed all of the from MODERATED_* to VERY_* (we need to
check nothing else is broken)

**Comment by AlexAmoSfC** [comment]
Exactly, that is my request. Since the functionality is fixed and the remains only have to do with code quality, would you prefer me to open a new issue just for this refactor alone? I think this change will not cause any problem at all but we could open a new issue for observation and followup purposes if you want.

**Comment by frasanz** [comment]
I did this refactor in the last commit

**Comment by AlexAmoSfC** [comment]
True. I was just suggesting to separate in a different issue and close it instantly for documentation purposes. Sorry if I did not explain myself correctly. if you are ok with this, we can close the topic. Thank you very much!
PS: don't forget to take a look at Jupyter notebook too. I have provided an auxiliary python module that you could be interested in checking out. I have uploaded an alternative version of your jupyter notebook that relies on this class and performs a considerable amount of fixes and transformations in a clean fashion.

**Comment by AlexAmoSfC** [comment]
Suggestion for all of those that have already generated excel files with observations:
mass search and replace the literal text "Moderate" for "Very"
