### ISSUE TITLE
Language issues in the annoyance and hedonic tone scales

### ISSUE THREAD

**Issue by miguelherpas** [Ibercivis/odourcollect.eu#77]
Good evening,

I was just checking the app and I've realized that when you want to create a new observation the language in the intensity and hedonic tone do not appear in the language that is selected. It only appears in English and it can be confusing for many users.

I include a couple of screenshots to help you localize the issue.

Thanks in advance. 

![image](https://user-images.githubusercontent.com/83075623/130123677-b6ff0081-7a60-4936-a3b0-f111f940335e.png)
![image](https://user-images.githubusercontent.com/83075623/130123755-592aee84-3c01-4715-9389-2685c8a114bb.png)

**Comment by AlexAmoSfC** [comment]
closing as this seems to be working OK at time
